### PR TITLE
feature: added freshness

### PR DESCRIPTION
**Pull request by avoloshko**

### CODE REVIEW

**Comment by ezlowx** [comment]
👍

**Review by DZariusz — CHANGES_REQUESTED** [review]
this is added to wrong file, please add it under `prod/`

**Comment by DZariusz** [comment]
whatsup with this PR? we need to support old path atm so we need to change all files that are in main branch

**Comment by DZariusz** [comment]
bumping question

**Comment by matheushahnn** [comment]
1year without interaction.

**Pull request closed without merging**
